---
title: "STAT 6170 Statistical Report"
output:
  pdf_document:
    keep_tex: no
    includes:
date: "`r Sys.Date()`"
subtitle: "STAT7123/STAT8123"
author: "Osbert Bryan T. Villasis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                  message = FALSE, 
                  warning = FALSE)
library(readr)
library(car)
```

\section{Abstract}

## Abstract

\section {Introduction}

## Introduction

\section {Methods}

## Methods

\section {Results}

## Preliminary Data Exploration

```{r, echo=FALSE}
#Data Verification

# Import the data from Excel
data <- read_csv("47826479_data_StatReport.csv")

# Check the first few rows to ensure it's loaded correctly
head(data)

# Shapiro-Wilk Test for Normality of Data
shapiro.test(data$weight[data$species == "Spotted"])
shapiro.test(data$weight[data$species == "Striped"])
shapiro.test(data$territory[data$species == "Spotted"])
shapiro.test(data$territory[data$species == "Striped"])

# Levene's Test for Homoscedasticity (Checking for Equal Variances)
leveneTest(weight ~ species, data=data)
leveneTest(territory ~ species, data=data)

# 
```

## Analyses

```{r, echo=FALSE}
#Difference in Average Albedo

# Separate the data by species
spotted_data <- subset(data, species == "Spotted")
striped_data <- subset(data, species == "Striped")

# Calculate the mean albedo for each species
mean_albedo_spotted <- mean(spotted_data$albedo)
mean_albedo_striped <- mean(striped_data$albedo)

print(paste("Mean albedo of Spotted Stoaches: ", mean_albedo_spotted))
print(paste("Mean albedo of Striped Stoaches: ", mean_albedo_striped))

#Relationship Between Weight and Territory

# Plotting the relationship for Spotted stoaches
plot(spotted_data$weight, spotted_data$territory, main="Spotted Stoaches: Weight vs. Territory", xlab="Weight", ylab="Territory")

# Plotting the relationship for Striped stoaches
plot(striped_data$weight, striped_data$territory, main="Striped Stoaches: Weight vs. Territory", xlab="Weight", ylab="Territory")

#Computation for Correlation
cor.test(data$weight[data$species == "Spotted"], data$territory[data$species == "Spotted"])
cor.test(data$weight[data$species == "Striped"], data$territory[data$species == "Striped"])
```

\section {Conclusions and Further Discussion}

## Conclusion

\section {References}

## References

\section {Appendix}

## Appendix
